<?php

use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * 
 */
function madness_query_sort_by_random_alter(AlterableInterface $query) {
  $query->orderRandom();
}

/**
 * 
 */
function madness_node_insert(EntityInterface $node) {
  if ((int) \Drupal::config('madness.settings')->get('increase_on_event_content')) {
    $users = \Drupal::service('madness.levels')->increaseMadness();
  }
}

/**
 * 
 */
function madness_node_update(EntityInterface $node) {
  if ((int) \Drupal::config('madness.settings')->get('increase_on_event_content')) {
    $users = \Drupal::service('madness.levels')->increaseMadness();
  }
}

/**
 * 
 */
function madness_cron() {
  if ((int) \Drupal::config('madness.settings')->get('increase_on_event_cron')) {
    $users = \Drupal::service('madness.levels')->increaseMadness();
  }
}
